# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.0"

      - name: Build
        run: go build -v ./...

      - name: Install KinD
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.24.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
      - name: Create KinD cluster
        run: kind create cluster
#    - name: Set up K3s
#      run: |
#          curl -sfL https://get.k3s.io | sh -
#          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
#          sudo chmod 644 /etc/rancher/k3s/k3s.yaml
#          sudo k3s server &
#          sudo kubectl get nodes
#          sudo k3s kubectl get node

# - name: Run Tests
#   run: |
#       go test -v ./...
